# <%= appNameSlug %>
# https://github.com/<%= userName %>/<%= appNameSlug %>
#
# Copyright (c) <%= year %>, <%= authorName %>
# Licensed under the <%= license %> license.


test:
	go test -v ./test

.PHONY: test